RedeMusica/Models/Musicas.cs
using System;
using MySql.Data.MySqlClient;
using mysqlPDS.classes;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.ComponentModel;
using System.Web.Mvc;
using System.Text;

namespace RedeMusica.Models
{
    public class Musicas
    {
        #region atributos       
        public int id{get;set;}

        public string usuarioNome{get;set;}
        public int usuarioId{get;set;}
        public int bandaId { get; set; }
        public string estiloNome {get;set;}
        //public Bandas banda;

        [Required(ErrorMessage = "Obrigatório informar o nome")]
        [StringLength(55, ErrorMessage = "O nome deve possuir no máximo 55 caracteres")]
        public string nome{get;set;}
        public string imageMusica{get;set;}

       
        public string arquivoMusica{get;set;}

        public DateTime dataPost{get;set;}
        public int nOuvida{get;set;}
      

        #endregion 

        public void MusicaUsuario(Musicas novo)
        {
            string sql = null;
            sql = "insert into Musicas(nomeMusica,Usuarios_idUsuario,usuario_nome,imagemMusica,arquivoMusica,dataPost,nOuvida,estilos_nome) Values(@nome,@usuario,@usuarioNome,@imagem,@musica,@data,@nOuvida,@estilos);";
            MySqlCommand comand = new MySqlCommand();
            comand.CommandText = sql;
            comand.Parameters.AddWithValue("@nome", novo.nome);
            comand.Parameters.AddWithValue("@usuario", novo.usuarioId);
            comand.Parameters.AddWithValue("@usuarioNome",novo.usuarioNome);
            comand.Parameters.AddWithValue("@imagem", novo.imageMusica);
            comand.Parameters.AddWithValue("@musica", novo.arquivoMusica);
            comand.Parameters.AddWithValue("@data", DateTime.Today);
            comand.Parameters.AddWithValue("@nOuvida", 0);
            comand.Parameters.AddWithValue("@estilos",novo.estiloNome); 
            MysqlPDS.ExecutarCommando(comand);
        }

        public void MusicaBanda(Musicas novo)
        {
            string sql = null;
            sql = "insert into Musicas(nomeMusica,Bandas_idBanda,usuario_nome,imagemMusica,arquivoMusica,dataPost,nOuvida,estilos_nome) Values(@nome,@usuario,@usuarioNome,@imagem,@musica,@data,@nOuvida,@estilos);";
            MySqlCommand comand = new MySqlCommand();
            comand.CommandText = sql;
            comand.Parameters.AddWithValue("@nome", novo.nome);
            comand.Parameters.AddWithValue("@usuario", novo.usuarioId);
            comand.Parameters.AddWithValue("@usuarioNome", novo.usuarioNome);
            comand.Parameters.AddWithValue("@imagem", novo.imageMusica);
            comand.Parameters.AddWithValue("@musica", novo.arquivoMusica);
            comand.Parameters.AddWithValue("@data", DateTime.Today);
            comand.Parameters.AddWithValue("@nOuvida", 0);
            comand.Parameters.AddWithValue("@estilos", novo.estiloNome);
            MysqlPDS.ExecutarCommando(comand);
        }

        public List<Musicas> Proprias(string id)
        {
            List<Musicas> lista = new List<Musicas>();
            string sql = "SELECT * FROM musicas WHERE Usuarios_idUsuario=@id;";
            MySqlCommand comand = new MySqlCommand();
            comand.CommandText = sql;
            Convert.ToInt32(id);
            comand.Parameters.AddWithValue("@id", id);
            var dr = MysqlPDS.getLista(comand);
            while (dr.Read())
            {
                Musicas atual = new Musicas();
                atual.id = dr.GetInt32(dr.GetOrdinal("idMusica"));
                atual.nome = dr.GetString(dr.GetOrdinal("nomeMusica"));
                atual.usuarioId = dr.GetInt32(dr.GetOrdinal("Usuarios_idUsuario"));
                atual.usuarioNome = dr.GetString(dr.GetOrdinal("usuario_nome"));
                atual.imageMusica = dr.GetString(dr.GetOrdinal("imagemMusica"));
                atual.arquivoMusica = dr.GetString(dr.GetOrdinal("arquivoMusica"));
                atual.dataPost = dr.GetDateTime(dr.GetOrdinal("dataPost"));
                atual.nOuvida = dr.GetInt32(dr.GetOrdinal("nOuvida"));
                atual.estiloNome = dr.GetString(dr.GetOrdinal("Estilos_nome"));
                lista.Add(atual);
            }
            dr.Dispose();
            return lista;
        }

        public List<Musicas> PropriasBanda(int id)
        {
            List<Musicas> lista = new List<Musicas>();
            string sql = "SELECT * FROM musicas WHERE Bandas_idBanda=@id;";
            MySqlCommand comand = new MySqlCommand();
            comand.CommandText = sql;
            comand.Parameters.AddWithValue("@id", id);
            var dr = MysqlPDS.getLista(comand);
            while (dr.Read())
            {
                Musicas atual = new Musicas();
                atual.id = dr.GetInt32(dr.GetOrdinal("idMusica"));
                atual.nome = dr.GetString(dr.GetOrdinal("nomeMusica"));
                atual.usuarioId = dr.GetInt32(dr.GetOrdinal("Bandas_idBanda"));
                atual.usuarioNome = dr.GetString(dr.GetOrdinal("usuario_nome"));
                atual.imageMusica = dr.GetString(dr.GetOrdinal("imagemMusica"));
                atual.arquivoMusica = dr.GetString(dr.GetOrdinal("arquivoMusica"));
                atual.dataPost = dr.GetDateTime(dr.GetOrdinal("dataPost"));
                atual.estiloNome = dr.GetString(dr.GetOrdinal("Estilos_nome"));

                atual.nOuvida = dr.GetInt32(dr.GetOrdinal("nOuvida"));
                lista.Add(atual);
            }
            dr.Dispose();
            return lista;
        }

        public static List<Musicas> estilo()
        {
            List<Musicas> listaEstilo = new List<Musicas>();
            string sql = "SELECT * FROM estilos;";
            MySqlCommand comand = new MySqlCommand();
            comand.CommandText = sql;
            var dr = MysqlPDS.getLista(comand);
            while(dr.Read())
            {
                Musicas atual = new Musicas();
                atual.estiloNome=dr.GetString(dr.GetOrdinal("nome"));
                listaEstilo.Add(atual);
            }
            dr.Close();
            return listaEstilo;
        }

        public List<Musicas> Todas(string id)
        {
            List<Musicas> lista = new List<Musicas>();
            string sql = "SELECT * FROM musicas WHERE Usuarios_idUsuario<>@id;";
            MySqlCommand comand = new MySqlCommand();
            comand.CommandText = sql;
            Convert.ToInt32(id);
            comand.Parameters.AddWithValue("@id", id);
            var dr = MysqlPDS.getLista(comand);
            while (dr.Read())
            {
                Musicas atual = new Musicas();
                atual.id = dr.GetInt32(dr.GetOrdinal("idMusica"));
                atual.nome = dr.GetString(dr.GetOrdinal("nomeMusica"));
                atual.usuarioId = dr.GetInt32(dr.GetOrdinal("Usuarios_idUsuario"));
                atual.usuarioNome = dr.GetString(dr.GetOrdinal("usuario_nome"));
                atual.imageMusica = dr.GetString(dr.GetOrdinal("imagemMusica"));
                atual.arquivoMusica = dr.GetString(dr.GetOrdinal("arquivoMusica"));
                atual.dataPost = dr.GetDateTime(dr.GetOrdinal("dataPost"));
                atual.estiloNome = dr.GetString(dr.GetOrdinal("Estilos_nome"));
                atual.nOuvida = dr.GetInt32(dr.GetOrdinal("nOuvida"));
                lista.Add(atual);
            }
            dr.Dispose();
            return lista;
        }
        public void Delete(int id)
        {
            string sql = "delete from musicas WHERE idMusica=@id;";
            MySqlCommand comand = new MySqlCommand();
            comand.CommandText = sql;
            comand.Parameters.AddWithValue("@id", id);
            MysqlPDS.ExecutarCommando(comand);
        }

        public List<Musicas> Busca(string buscando)
        {
           
         
            List<Musicas> lista = new List<Musicas>();
            if (buscando == "")
            {
                return lista;
            }
            string sql = "SELECT * FROM musicas WHERE Usuarios_idUsuario Is not null and nomeMusica  LIKE  @buscando  or estilos_nome Like @buscando and Usuarios_idUsuario Is not null;";
            MySqlCommand comand = new MySqlCommand();
            comand.CommandText = sql;
            comand.Parameters.AddWithValue("@buscando", "%" + buscando + "%");
            var dr = MysqlPDS.getLista(comand);
            while (dr.Read())
            {
                Musicas atual = new Musicas();
                atual.id = dr.GetInt32(dr.GetOrdinal("idMusica"));
                atual.nome = dr.GetString(dr.GetOrdinal("nomeMusica"));
                atual.usuarioId = dr.GetInt32(dr.GetOrdinal("Usuarios_idUsuario"));
                atual.usuarioNome = dr.GetString(dr.GetOrdinal("usuario_nome"));
                atual.imageMusica = dr.GetString(dr.GetOrdinal("imagemMusica"));
                atual.arquivoMusica = dr.GetString(dr.GetOrdinal("arquivoMusica"));
                atual.dataPost = dr.GetDateTime(dr.GetOrdinal("dataPost"));
                atual.estiloNome = dr.GetString(dr.GetOrdinal("Estilos_nome"));
                atual.nOuvida = dr.GetInt32(dr.GetOrdinal("nOuvida"));
                lista.Add(atual);
            }
            dr.Dispose();
            return lista;
        }

        public List<Musicas> BuscaMusicaBanda(string buscando)
        {
            
            List<Musicas> lista = new List<Musicas>();
            if (buscando == "")
            {
                return lista;
            }
            string sql = "SELECT * FROM musicas WHERE Bandas_idBanda Is not null and nomeMusica  LIKE  @buscando  or estilos_nome Like @buscando and Bandas_idBanda Is not null;";
            MySqlCommand comand = new MySqlCommand();
            comand.CommandText = sql;
            comand.Parameters.AddWithValue("@buscando", "%" + buscando + "%");

RedeMusica/Controllers/MusicasController.cs
using RedeMusica.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RedeMusica.Controllers
{
    public class MusicasController : Controller
    {
        // GET: Musicas
        Musicas atual = new Musicas();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult DeleteMusica(int idM)
        {
            atual.Delete(idM);
            return RedirectToAction("PerfilIni","Usuarios");
        }  
        
        public ActionResult MusicaUsuario()
        {
            if (Session["idUsuario"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult MusicaUsuario(Musicas novo, HttpPostedFileBase fileImagem, HttpPostedFileBase fileMusica)
        {
            String caminhoF = null;
            String caminhoM = null;
            if (!ModelState.IsValid)
            {
                return View();
            }
            else
            {
                if (fileImagem != null && fileImagem.ContentLength > 0)
                {
                     string ext = Path.GetExtension(fileImagem.FileName);
                     if (String.IsNullOrEmpty(ext) || !ext.Equals(".jpg", StringComparison.OrdinalIgnoreCase) || fileImagem == null)
                     {
                         ViewBag.Imagem = "Somente imagens .jpg";
                         return View("MusicaUsuario");
                     }
                     else
                     {
                         var fileName = Path.GetFileName(fileImagem.FileName);
                         string novas = fileName.Replace(" ", "");
                         var path = Path.Combine(Server.MapPath("~/ImagemMusica"), novas);
                         fileImagem.SaveAs(path);
                         caminhoF = "~/ImagemMusica/" + novas.ToString();
                         novo.imageMusica = caminhoF;
                     }
                }

                else
                {
                    caminhoF = "~/Filtros/musica.png"; ;
                    novo.imageMusica = caminhoF;
                }
                if (fileMusica!= null && fileMusica.ContentLength > 0)
                {
                    string ext = Path.GetExtension(fileMusica.FileName);
                    if (String.IsNullOrEmpty(ext) || !ext.Equals(".mp3", StringComparison.OrdinalIgnoreCase) || fileMusica==null)
                    {
                        ViewBag.Musica = "Somente arquivos mp3";
                        return View("MusicaUsuario");
                    }
                    else
                    {
                        
                        var fileName = Path.GetFileName(fileMusica.FileName);
                        string nova = fileName.Replace(" ", "");
                      
                        var path = Path.Combine(Server.MapPath("~/Musicas"), nova);
                        fileMusica.SaveAs(path);
                        caminhoM = "~/Musicas/" + nova.ToString();
                        novo.arquivoMusica = caminhoM;
                        novo.usuarioId = Convert.ToInt32(Session["idUsuario"]) ;
                        novo.usuarioNome = Session["NomeCompleto"].ToString();
                        atual.MusicaUsuario(novo);
                        return RedirectToAction("PerfilIni", "Usuarios");
                    }
                }
                ViewBag.Musica = "Somente arquivos mp3";
                return View("MusicaUsuario");
            }
        }
        public ActionResult MusicaBanda()
        {
            if (Session["idUsuario"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult MusicaBanda(Musicas novo, HttpPostedFileBase fileImagem, HttpPostedFileBase fileMusica)
        {
            String caminhoF = null;
            String caminhoM = null;
            if (!ModelState.IsValid)
            {
                return View();
            }
            else
            {
                if (fileImagem != null && fileImagem.ContentLength > 0)
                {
                    string ext = Path.GetExtension(fileImagem.FileName);
                    if (String.IsNullOrEmpty(ext) || !ext.Equals(".jpg", StringComparison.OrdinalIgnoreCase) || fileImagem == null)
                    {
                        ViewBag.Imagem = "Somente imagens .jpg";
                        return View("MusicaBanda");
                    }
                    else
                    {
                        var fileName = Path.GetFileName(fileImagem.FileName);
                        string novas = fileName.Replace(" ", "");
                        var path = Path.Combine(Server.MapPath("~/ImagemMusica"), novas);
                        fileImagem.SaveAs(path);
                        caminhoF = "~/ImagemMusica/" + novas.ToString();
                        novo.imageMusica = caminhoF;
                    }
                }

                else
                {
                    caminhoF = "~/Filtros/musica.png";
                    novo.imageMusica = caminhoF;
                }
                if (fileMusica != null && fileMusica.ContentLength > 0)
                {
                    string ext = Path.GetExtension(fileMusica.FileName);
                    if (String.IsNullOrEmpty(ext) || !ext.Equals(".mp3", StringComparison.OrdinalIgnoreCase) || fileMusica == null)
                    {
                        ViewBag.Musica = "Somente músicas .mp3";
                        return View("MusicaBanda");
                    }
                    else
                    {
                        var fileName = Path.GetFileName(fileMusica.FileName);
                        string nova = fileName.Replace(" ", "");
                        var path = Path.Combine(Server.MapPath("~/Musicas"), nova);
                        fileMusica.SaveAs(path);
                        caminhoM = "~/Musicas/" + nova.ToString();
                        novo.arquivoMusica = caminhoM;
                        novo.usuarioId = Convert.ToInt32(Session["idBanda"]); ;
                        novo.usuarioNome = Session["nomeBanda"].ToString();
                        atual.MusicaBanda(novo);
                        return RedirectToAction("Perfil", "Bandas", new { id = novo.usuarioId });
                    }
                }
                ViewBag.Musica = "Somente arquivos mp3";
                return View("MusicaBanda");
            }
        }

       
       

        public ActionResult Proprias()
        {
            string id= Session["idUsuario"].ToString();
            List<Musicas> lista = new List<Musicas>();
            lista= atual.Proprias(id);
            return View(lista);
        }

        

        public ActionResult Todas()
        {
            string id = Session["idUsuario"].ToString();
            List<Musicas> lista = new List<Musicas>();
            lista = atual.Todas(id);
            return View(lista);
        }

        public ActionResult MusicasUsers()
        {
            string id = Session["idUsuarioAtual"].ToString();
            List<Musicas> lista = new List<Musicas>();
            lista = atual.Proprias(id);
            return View(lista);

        }
       
       

       

    }
}

RedeMusica/Views/Musicas/Delete.cshtml
@model<RedeMusica.Models.Musicas>

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Musicas</h4>
    <hr />
    <dl class="dl-horizontal">

   
     @foreach (var item in model) {


        <dt>
            @Html.DisplayNameFor()
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nomeMusica)
        </dd>

        
     }
        
      

        

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

RedeMusica/Views/Musicas/DeleteMusica.cshtml
@model RedeMusica.Models.Musicas

@{
    ViewBag.Title = "DeleteMusica";
}

<h2>DeleteMusica</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Musicas</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Deletar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "PerfilIni","Usuarios")
</div>

RedeMusica/Views/Musicas/MusicaBanda.cshtml
@model RedeMusica.Models.Musicas

@using System.Collections.Generic
@{
    ViewBag.Title = "MusicaBanda";
}

<h2>Adicionar Música</h2>


@using (Html.BeginForm("MusicaBanda", "Musicas", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Imagem: <input type="file" name="fileImagem" />
        </div>

        <div class="form-group">
            música: <input type="file" name="fileMusica" />
        </div>

        <div>
            Estilo:
            <select name="estiloNome" id="estiloNome">
                @{
    List<RedeMusica.Models.Musicas> lista = new List<RedeMusica.Models.Musicas>();
    lista = RedeMusica.Models.Musicas.estilo();

                }
                @foreach (var item in lista)
                {
                    <option value="@item.estiloNome">@item.estiloNome</option>
                }

            </select>
        </div>


    </div>
    <br />

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Postar música" class="btn btn-default" />
        </div>
    </div>

}


@section Scripts {
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
    @Scripts.Render("~/bundles/jqueryval")
}



@if (ViewBag.Musica != null)
{
    <script type="text/javascript">



            alert('@ViewBag.Musica');



    </script>

}
@if (ViewBag.Imagem != null)
{
    <script type="text/javascript">



        alert('@ViewBag.Imagem');



    </script>
}

RedeMusica/Views/Musicas/MusicaUsuario.cshtml
@model RedeMusica.Models.Musicas

@using System.Collections.Generic
@{
    ViewBag.Title = "MusicaUsuario";
}

<h2>Adicionar Música</h2>


@using (Html.BeginForm("MusicaUsuario", "Musicas", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
       
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
       
        <div class="form-group">
            @Html.LabelFor(model => model.nome, htmlAttributes: new { @class = "control-label col-sm-1 " })
            <div class="col-md-4">
                @Html.EditorFor(model => model.nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="margin-left:3%">
            Imagem: <input type="file" name="fileImagem" />
        </div>

        <div class="form-group" style="margin-left:3%">
            música: <input type="file" name="fileMusica" />
        </div>
       
        <div style="margin-left:3%">
            Estilo:
            <select name="estiloNome" id="estiloNome" style="margin-left:1%">
                @{
    List<RedeMusica.Models.Musicas> lista = new List<RedeMusica.Models.Musicas>();
    lista = RedeMusica.Models.Musicas.estilo();

                }
                @foreach (var item in lista)
                {
                    <option value="@item.estiloNome">@item.estiloNome</option>
                }

            </select>

        </div>
      
            
        </div>
 <br />
    
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Postar música" class="btn btn-default" />
            </div>
        </div>
   
}


@section Scripts {
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
    @Scripts.Render("~/bundles/jqueryval")
}



@if (ViewBag.Musica != null)
{
    <script type="text/javascript">

        

            alert('@ViewBag.Musica');

        

    </script>

}
@if (ViewBag.Imagem != null)
{
    <script type="text/javascript">



        alert('@ViewBag.Imagem');



    </script>
}

RedeMusica/Views/Musicas/Proprias.cshtml
@model IEnumerable<RedeMusica.Models.Musicas>

@{
    ViewBag.Title = "Proprias";
}

<h2>Proprias</h2>

<p>
    @Html.ActionLink("Create New", "MusicaUsuario","Musicas")
</p>
<table class="tg" style="undefined;table-layout: fixed; width: 330px">


    @foreach (var item in Model)
    {
        string foto = item.imageMusica.ToString();
        string musica = item.arquivoMusica.ToString();


        <colgroup>
            <col style="width: 119px">
            <col style="width: 106px">
            <col style="width: 105px">
        </colgroup>
        <tr>
            <th class="tg-031e" rowspan="4"><img src=@Url.Content(foto) style="width:128px;height:128px" /></th>
            <th class="tg-031e" colspan="2">@Html.DisplayFor(modelItem => item.nome)</th>
        </tr>
        <tr>
            <td class="tg-031e" colspan="2">@Html.DisplayFor(modelItem => item.usuarioNome)</td>
        </tr>
        <tr>
            <td class="tg-031e" colspan="2">
                <audio controls id="audioplayer">
                    <source src=@Url.Content(musica) type="audio/mp3" />
                    sem audio
                </audio>
            </td>
        </tr>
        <tr>
            <td class="tg-031e">Ouvida @Html.DisplayFor(modelItem => item.nOuvida)</td>
            <td class="tg-031e">@Html.DisplayFor(modelItem => item.dataPost)</td>
        </tr>
  





    
}

</table>

RedeMusica/Views/Musicas/Todas.cshtml
@model IEnumerable<RedeMusica.Models.Musicas>

@{
   
    ViewBag.Title = "Todas";
}

<h2>Todas</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.estiloNome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.imageMusica)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.arquivoMusica)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.dataPost)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nOuvida)
        </th>
        <th>
           
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.estiloNome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.imageMusica)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.arquivoMusica)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.dataPost)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.nOuvida)
        </td>
            @Html.ActionLink("Perfil", "Usuarios", "Perfil", new {id=item.usuarioId })
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>

RedeMusica/Views/Musicas/asdasd.cshtml
@model IEnumerable<RedeMusica.Models.Musicas>

@{
    ViewBag.Title = "asdasd";
}

<h2>asdasd</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.usuarioNome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.usuarioId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.bandaId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.estiloNome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.imageMusica)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.arquivoMusica)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.dataPost)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nOuvida)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.usuarioNome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.usuarioId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.bandaId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.estiloNome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.imageMusica)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.arquivoMusica)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.dataPost)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.nOuvida)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>