RedeMusica/Models/Equipamentos.cs
using System;
using System.Collections.Generic;
using MySql.Data.MySqlClient;
using mysqlPDS.classes;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace RedeMusica.Models
{
    public class Equipamentos
    {
        public int id { get; set; }

        public string arquivoFoto { get; set; }
        public string thumbnail { get; set; }
        public string usuarioId { get; set; }

        [StringLength(55, ErrorMessage = "Máximo 55 caracteres")]
        public string descricao { get; set; }

        public void Adicionar(Equipamentos novo)
        {

            string sql = null;
            sql = "insert into Equipamentos(Usuarios_idUsuario,descricao,arquivoFoto,thumbnail) Values(@user,@desc,@arquivo,@thumbnail);";
            MySqlCommand comand = new MySqlCommand();
            comand.CommandText = sql;
            comand.Parameters.AddWithValue("@user", novo.usuarioId);
            comand.Parameters.AddWithValue("@desc", novo.descricao);
            comand.Parameters.AddWithValue("@arquivo", novo.arquivoFoto);
            comand.Parameters.AddWithValue("@thumbnail", novo.thumbnail);
            MysqlPDS.ExecutarCommando(comand);
        }
        public List<Equipamentos> getUserEquips(int id)
        {
            List<Equipamentos> lista = new List<Equipamentos>();
            string sql = "SELECT * FROM equipamentos WHERE Usuarios_idUsuario=@id;";
            MySqlCommand comand = new MySqlCommand();
            comand.CommandText = sql;
            comand.Parameters.AddWithValue("@id", id);
            var dr = MysqlPDS.getLista(comand);
            while (dr.Read())
            {
                Equipamentos atual = new Equipamentos();
                atual.id = dr.GetInt32(dr.GetOrdinal("idEquip"));
                atual.descricao = dr.GetString(dr.GetOrdinal("descricao"));
                atual.arquivoFoto = dr.GetString(dr.GetOrdinal("arquivoFoto"));
                atual.thumbnail = dr.GetString(dr.GetOrdinal("thumbnail"));
                lista.Add(atual);
            }
            dr.Dispose();
            return lista;
        }

        public void Delete(int id)
        {
            string sql = "delete from equipamentos WHERE idEquip=@id;";
            MySqlCommand comand = new MySqlCommand();
            comand.CommandText = sql;
            comand.Parameters.AddWithValue("@id", id);
            MysqlPDS.ExecutarCommando(comand);
        }
    }
}

RedeMusica/Controllers/EquipamentosController.cs
using System;
using ImageResizer;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RedeMusica.Models;

namespace RedeMusica.Controllers
{
    public class EquipamentosController : Controller
    {
        // GET: Equipamentos

        Equipamentos equip = new Equipamentos();
        public ActionResult AdicinarEquip()
        {
            if (Session["idUsuario"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult AdicinarEquip(Equipamentos novo, HttpPostedFileBase file)
        {
            if (!ModelState.IsValid)
            {
                return View("AdicionarEquip");
            }
            else
            {
                if (novo.descricao == null)
                    novo.descricao = "Sem legenda";
                if (file != null && file.ContentLength > 0)
                {

                    string ext = Path.GetExtension(file.FileName);
                    if (String.IsNullOrEmpty(ext) || !ext.Equals(".jpg", StringComparison.OrdinalIgnoreCase) || file == null)
                    {
                        ViewBag.ImagemE = "Somente imagens .jpg";
                        return View("AdicinarEquip");
                    }
                    var fileName = Path.GetFileName(file.FileName);
                    string nova = fileName.Replace(" ", "");
                    var path = Path.Combine(Server.MapPath("~/ImagemEquipamento"), nova);
                    file.SaveAs(path);
                    String caminho = "~/ImagemEquipamento/" + nova.ToString();
                    novo.arquivoFoto = caminho;
                    novo.usuarioId = Convert.ToString(Session["idUsuario"]);
                    var thumbnail = new ImageJob(file, "~/Thumbnails/<guid>", new Instructions("mode=max;format=jpg;width=300;height=300;"));
                    thumbnail.CreateParentDirectory = true;
                    thumbnail.AddFileExtension = true;
                    thumbnail.Build();
                    fileName = Path.GetFileName(thumbnail.FinalPath);
                    novo.thumbnail = Url.Content("~/Thumbnails/" + fileName);
                    equip.Adicionar(novo);
                }
                else
                {
                    ViewBag.ImagemE = "Somente imagens .jpg";
                    return View("AdicinarEquip");
                }

                return RedirectToAction("PerfilIni", "Usuarios");
            }
            }
        public ActionResult DeleteEquip()
        {
            if (Session["idUsuario"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
             List<RedeMusica.Models.Equipamentos> listaEquips = new List<RedeMusica.Models.Equipamentos>();
             listaEquips = equip.getUserEquips(Convert.ToInt32(Session["idUsuario"]));
            return View(listaEquips);
            
          }
  
        
        public ActionResult DeleteEquips(int id)
        {
            equip.Delete(id);
            return RedirectToAction("DeleteEquip");
        }

    }
}

RedeMusica/Views/Equipamentos/AdicinarEquip.cshtml
@model RedeMusica.Models.Equipamentos

@{
    ViewBag.Title = "AdicinarEquip";
}

<h2>Adicinar Equipamento</h2>


@using (Html.BeginForm("AdicinarEquip", "Equipamentos", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
       <div class="form-group">
        @Html.LabelFor(model => model.descricao, htmlAttributes: new { @class = "control-label col-sm-1 " })
        <div class="col-md-4">
            @Html.EditorFor(model => model.descricao, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.descricao, "", new { @class = "text-danger" })
        </div>
    </div>

        <div class="form-group" style="margin-left:1%">
            Imagem: <input type="file" name="file" />
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Adicionar" class="btn btn-default" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

@if (ViewBag.ImagemE != null)
{
    <script type="text/javascript">



        alert('@ViewBag.ImagemE');



    </script>
}

RedeMusica/Views/Equipamentos/DeleteEquip.cshtml
@model IEnumerable<RedeMusica.Models.Equipamentos>

@{
    ViewBag.Title = "DeleteEquip";
}

<h2>Delete Equipamento</h2>


<table class="table">
    <tr>
        <th>
            Foto
        </th>
        <th>
            @Html.DisplayNameFor(model => model.descricao)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    string thumb = item.thumbnail.ToString();
      <tr>
        <td>
            <img style="width: 30%" src=@Url.Content(thumb)>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.descricao)
        </td>
        <td>
            @Html.ActionLink("Delete", "DeleteEquips", new { id=item.id })
        </td>
    </tr>
}

</table>