RedeMusica/Controllers/BandasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RedeMusica.Models;
using System.IO;

namespace RedeMusica.Controllers
{
    public class BandasController : Controller
    {
        Bandas atual = new Bandas();
        // GET: Bandas
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Criar()
        {
            if (Session["idUsuario"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Criar(Bandas novo, HttpPostedFileBase fileImagem)
        {
            String caminhoF = null;

            if (!ModelState.IsValid)
            {
                return View("Criar");
            }
            else
            {
                if (fileImagem != null && fileImagem.ContentLength > 0)
                {
                    string ext = Path.GetExtension(fileImagem.FileName);
                    if (String.IsNullOrEmpty(ext) || !ext.Equals(".jpg", StringComparison.OrdinalIgnoreCase) || fileImagem == null)
                    {
                        ViewBag.Musica = "Somente arquivos .jpg";
                        return View("MusicaUsuario");
                    }
                    else
                    {
                        var fileName = Path.GetFileName(fileImagem.FileName);
                        string novas = fileName.Replace(" ", "");
                        var path = Path.Combine(Server.MapPath("~/ImagemBanda"), novas);
                        fileImagem.SaveAs(path);
                        caminhoF = "~/ImagemBanda/" + novas.ToString();
                        novo.foto = caminhoF;
                        novo.idUsuario = Convert.ToInt32(Session["idUsuario"]);
                        atual.Criar(novo);
                        return RedirectToAction("PerfilIni", "Usuarios");
                    }
                }

                else
                {
                    caminhoF = "~/Filtros/banda.png";
                    novo.foto = caminhoF;
                    novo.idUsuario = Convert.ToInt32(Session["idUsuario"]);
                    atual.Criar(novo);
                    return RedirectToAction("PerfilIni", "Usuarios");
                }

            }
        }
        [HttpPost]
        public ActionResult BuscarUsers(string buscando)
        {
            Usuarios user = new Usuarios();
            Bandas atuali = atual.PegaBanda(Session["idBanda"].ToString());
            Session["buscando"] = buscando;
            return View(atuali);
        }



        public ActionResult AdicionaIntegrante(int id)
        {
            atual.AdicionarIntegrante(id, Convert.ToInt32(Session["idBanda"]));
            return RedirectToAction("PerfilIni", "Usuarios");
        }

        public ActionResult removeUser(int idR)
        {
            atual.DeletarIntegrante(idR, Convert.ToInt32(Session["idBanda"]));
            return RedirectToAction("PerfilIni", "Usuarios");
        }

        public ActionResult Perfil(int id)
        {
            bool lider = false;
            string ids;
            ids = Convert.ToString(id);
            atual = atual.PegaBanda(ids);
            lider = atual.verificaUser(Convert.ToInt32(Session["idUsuario"]), id);
            if (lider == true)
            {
                Session["idBanda"] = id;
                Session["nomeBanda"] = atual.nome;
                return View("PerfilLiders", atual);
            }
            else
            {
                ViewBag.Seguindo = false;
                Session["idBanda"] = id;
                ViewBag.Seguindo = RedeMusica.Models.Usuarios.VerificaBandaSeguir(Convert.ToInt32(Session["idUsuario"]), Convert.ToInt32(Session["idBanda"]));
                return View(atual);
            }

        }

        public ActionResult unfollowBanda(int idBandaUnf)
        {
            Usuarios user = new Usuarios();
            user.UnfollowBanda(Convert.ToInt32(Session["idUsuario"]), idBandaUnf);
            return RedirectToAction("PerfilIni", "Usuarios");
        }

        public ActionResult followBanda(int idBandaf)
        {
            Usuarios user = new Usuarios();
            user.SeguirBanda(Convert.ToInt32(Session["idUsuario"]), idBandaf);
            return RedirectToAction("PerfilIni", "Usuarios");
        }
        public ActionResult BuscaUserBanda(string busca)
        {
            Bandas banda = new Bandas();
            Bandas atual = banda.PegaBanda(Session["idBanda"].ToString());
            Session["buscando"] = busca;
            return View(atual);
        }

        public ActionResult ConfigBanda()
        {
            if (Session["idUsuario"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            Bandas deAgora = atual.PegaBanda(Session["idBanda"].ToString());
            return View(deAgora);
        }

        public ActionResult DeleteBanda()
        {
            if (Session["idUsuario"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            atual.DeletarBanda(Convert.ToInt32(Session["idBanda"]));
  
            return RedirectToAction("PerfilIni", "Usuarios");
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult ConfigBanda(Bandas atual, HttpPostedFileBase fileImagem)
        {
            String caminhoF = null;
            Bandas qse = new Bandas();
            if (atual.nome == null || atual.cidadeNatal == null)
            {
                return View("ConfigBanda");
            }
            else
            {
                if (fileImagem != null && fileImagem.ContentLength > 0)
                {
                    string ext = Path.GetExtension(fileImagem.FileName);
                    if (!ext.Equals(".jpg", StringComparison.OrdinalIgnoreCase))
                    {
                        ViewBag.Imagem = "Somente imagens .jpg";
                        return View("ConfigBanda");
                    }
                    else
                    {
                        var fileName = Path.GetFileName(fileImagem.FileName);
                        string novas = fileName.Replace(" ", "");
                        var path = Path.Combine(Server.MapPath("~/ImagemBanda"), novas);
                        fileImagem.SaveAs(path);
                        caminhoF = "~/ImagemBanda/" + novas.ToString();
                        atual.foto = caminhoF;
                        qse.AtualizaFoto(atual);
                        qse.editar(atual);
                        return RedirectToAction("PerfilIni", "Usuarios");
                    }
                }

                else
                {
                    qse.editar(atual);
                    return RedirectToAction("PerfilIni", "Usuarios");
                }
            }

        }
    }
}

RedeMusica/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using RedeMusica.Models;
using System.Web.Mvc;

namespace RedeMusica.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(Usuarios login)
        {
            Usuarios conectado = login.loginUser(login.email, login.senha);
            if (conectado != null)
            {
                Session["idUsuario"] = conectado.id;
                return RedirectToAction("PerfilIni", "Usuarios");
            }
            else
            {
               
                return RedirectToAction("PerfilIni","Usuarios");
            }
        }
        public ActionResult Acesso()
        {
            return View();
        }
       
        [HttpPost]
        public ActionResult Buscar(string buscando)
        {
            if(Session["idUsuario"]==null)
            {

                ViewBag.ErroLogin = "Você não está logado.";
                return RedirectToAction("Index", "Home");
            }
            Usuarios user = new Usuarios();
            Usuarios atual = user.PegaUser(Session["idUsuario"].ToString());
            Session["NomeCompleto"] = atual.nome + " " + atual.sobreNome;
            Session["buscando"] = buscando;
            return View(atual);
        }
      
    }
}

RedeMusica/Views/Home/Buscar.cshtml
@model RedeMusica.Models.Usuarios
@{
    ViewBag.Title = "busca";
    string foto = Model.fotoPerfil;
}

<br />
<br />
<div class="container">
    <div class="row">
        <div class="col col-sm-3">
            <div>
                <div id="sidebar">
                    <ul class="nav nav-stacked">
                        <li><h3 class="highlight">@Html.DisplayFor(atual => Model.nome) @Html.DisplayFor(atual => Model.sobreNome) </h3></li>
                        <li><img src=@Url.Content(foto) style="width:200px;height:200px" /> </li>
                        <li>@Html.DisplayFor(atual => Model.email)</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col col-sm-7">
            <div id="content">
                <ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
                    <li class="active"><a href="#red" data-toggle="tab">Músicas usuários</a></li>
                    <li><a href="#purpleRain" data-toggle="tab">Músicas Bandas</a></li>
                    <li><a href="#orange" data-toggle="tab">Usuários</a></li>
                    <li><a href="#hotline" data-toggle="tab"> Bandas</a></li>
                  
                </ul>
                <div id="my-tab-content" class="tab-content">
                    
                    <div class="tab-pane active" id="red">

                        <br />
                        @{
                            RedeMusica.Models.Musicas Musica = new RedeMusica.Models.Musicas();
                            List<RedeMusica.Models.Musicas> listaM = new List<RedeMusica.Models.Musicas>();
                            listaM = Musica.Busca(Session["buscando"].ToString());
                        }

                        <table style="table-layout: fixed; width: 400px">


                            @foreach (var item in listaM)
                            {
                                string fotoM = item.imageMusica.ToString();
                                string musica = item.arquivoMusica.ToString();
                                string nome = item.usuarioNome.ToString();
                                string data = item.dataPost.ToShortDateString();

                                <tr>
                                    <th rowspan="4"> <img src=@Url.Content(fotoM) style="width:128px;height:128px" /> </th>
                                    <th colspan="2">@Html.DisplayFor(modelItem => item.nome)</th>
                                </tr>
                                <tr>
                                    @if (item.bandaId == null)
                                    {
                                        <td colspan="2">@Html.ActionLink(nome, "Perfil", "Usuarios", new { id = item.usuarioId }, null) </td>
                                    }
                                    else
                                    {
                                        <td colspan="2">@Html.ActionLink(nome, "Perfil", "Bandas", new { id = item.bandaId }, null)</td>
                                    }
                                </tr>
                                <tr>
                                    <td colspan="2">
                                        <audio controls id="audioplayer">
                                            <source src=@Url.Content(musica) type="audio/mp3" />
                                            sem audio
                                        </audio>
                                    </td>
                                </tr>
                                <tr>
                                    <td> @Html.DisplayFor(modelItem => item.estiloNome)</td>
                                    <td>@data</td>
                                </tr>

                            }

                        </table>



                    </div>
                    <div class="tab-pane" id="purpleRain">
                        <br />
                        @{
                            RedeMusica.Models.Musicas MusicaBanda = new RedeMusica.Models.Musicas();
                            List<RedeMusica.Models.Musicas> listaMBanda = new List<RedeMusica.Models.Musicas>();
                            listaMBanda = Musica.BuscaMusicaBanda(Session["buscando"].ToString());
                        }

                        <table style="table-layout: fixed; width: 400px">


                            @foreach (var item in listaMBanda)
                            {
                                string fotoM = item.imageMusica.ToString();
                                string musica = item.arquivoMusica.ToString();
                                string nome = item.usuarioNome.ToString();
                                string data = item.dataPost.ToShortDateString();


                                <tr>
                                    <th rowspan="4"> <img src=@Url.Content(fotoM) style="width:128px;height:128px" /> </th>
                                    <th colspan="2">@Html.DisplayFor(modelItem => item.nome)</th>
                                </tr>
                                <tr>

                                    <td colspan="2">@Html.ActionLink(nome, "Perfil", "Bandas", new { id = item.usuarioId }, null) </td>
                                </tr>
                                <tr>
                                    <td colspan="2">
                                        <audio controls id="audioplayer">
                                            <source src=@Url.Content(musica) type="audio/mp3" />
                                            sem audio
                                        </audio>
                                    </td>
                                </tr>
                                <tr>
                                    <td> @Html.DisplayFor(modelItem => item.estiloNome)</td>
                                    <td>@data</td>
                                </tr>

                            }

                        </table>

                    </div>
                    <div class="tab-pane" id="orange">
                        @{
                            RedeMusica.Models.Usuarios user = new RedeMusica.Models.Usuarios();
                            List<RedeMusica.Models.Usuarios> listaUsers = new List<RedeMusica.Models.Usuarios>();
                            listaUsers = RedeMusica.Models.Usuarios.BuscaUser(Session["buscando"].ToString());
                        }
                        
                            @foreach (var item in listaUsers)
                            {
                                string fotoPosts = item.fotoPerfil.ToString();
                                string nome = item.nome;
                                <br />
                                <div class="media">
                                    <a class="media-left pull-left" href="#">
                                        <img src=@Url.Content(fotoPosts) style="width:128px;height:128px">
                                    </a>
                                    <div class="media-body">
                                        <h4 class="media-heading">@Html.ActionLink(nome, "Perfil", "Usuarios", new { id = item.id }, null)</h4>
                                       
                                    </div>
                                </div>
                            }
                        
                    </div>
                    <div id="hotline" class="tab-pane">
                    @{
                        RedeMusica.Models.Bandas suasBandas = new RedeMusica.Models.Bandas();
                        List<RedeMusica.Models.Bandas> listaSuasBandas = new List<RedeMusica.Models.Bandas>();
                        listaSuasBandas = suasBandas.Busca(Session["buscando"].ToString());
                    }


                    @foreach (var item in listaSuasBandas)
                    {
                        string fotoBanda = item.foto.ToString();
                        string nome = item.nome;
                        <br />
                        <div class="media">
                            <a class="media-left pull-left" href="#">
                                <img src=@Url.Content(fotoBanda) style="width:128px;height:128px">
                            </a>
                            <div class="media-body">
                                <h4 class="media-heading">@Html.ActionLink(nome, "Perfil", "Bandas", new { id = item.id }, null)</h4>
                                @item.cidadeNatal
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
</div>

RedeMusica/Views/Home/Index.cshtml
@model RedeMusica.Models.Usuarios
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Inicio</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body >
    <div class="clearfix">
        <div class="pull-right  ">
            <div class="jumbotron" style="border-radius: 15px;">

                <h3>Bem Vindo!</h3>
                @using (Html.BeginForm())
                {
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="input-group" style="margin-bottom: 8px;">
                        @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label" })
                        <div>
                            @Html.TextBoxFor(model => model.email, new { @class = "form-control" })
                        </div>
                    </div>

                    <div class="input-group">
                        @Html.LabelFor(model => model.senha, htmlAttributes: new { @class = "control-label" })
                        <div>
                            @Html.EditorFor(model => model.senha, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.senha, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <br />
                    <div class="btn" style="width: 100%;">
                        <button type="submit" class="btn btn-default">Login</button>
                        <a type="button" href="@Url.Action("Cadastro", "Usuarios")" class="btn btn-default">Faça parte</a>
                    </div>
                }

            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    @if (ViewBag.ErroLogin != null)
    {
        <script type="text/javascript">



            alert('@ViewBag.ErroLogin');



        </script>
    }


    <style type="text/css">
        body {
            background-image: url(../../Filtros/daumcapa.jpg);
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
        }
    </style>

    <script type="text/javascript">
        $(window).load(function () {
            $('body').css('min-height', $(window).height());
        });
        $(window).resize(function () {
            $('body').css('min-height', $(window).height());
        });
    </script>
   

</body>

</html>


}