RedeMusica/Controllers/BandasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RedeMusica.Models;
using System.IO;

namespace RedeMusica.Controllers
{
    public class BandasController : Controller
    {
        Bandas atual = new Bandas();
        // GET: Bandas
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Criar()
        {
            if (Session["idUsuario"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Criar(Bandas novo, HttpPostedFileBase fileImagem)
        {
            String caminhoF = null;

            if (!ModelState.IsValid)
            {
                return View("Criar");
            }
            else
            {
                if (fileImagem != null && fileImagem.ContentLength > 0)
                {
                    string ext = Path.GetExtension(fileImagem.FileName);
                    if (String.IsNullOrEmpty(ext) || !ext.Equals(".jpg", StringComparison.OrdinalIgnoreCase) || fileImagem == null)
                    {
                        ViewBag.Musica = "Somente arquivos .jpg";
                        return View("MusicaUsuario");
                    }
                    else
                    {
                        var fileName = Path.GetFileName(fileImagem.FileName);
                        string novas = fileName.Replace(" ", "");
                        var path = Path.Combine(Server.MapPath("~/ImagemBanda"), novas);
                        fileImagem.SaveAs(path);
                        caminhoF = "~/ImagemBanda/" + novas.ToString();
                        novo.foto = caminhoF;
                        novo.idUsuario = Convert.ToInt32(Session["idUsuario"]);
                        atual.Criar(novo);
                        return RedirectToAction("PerfilIni", "Usuarios");
                    }
                }

                else
                {
                    caminhoF = "~/Filtros/banda.png";
                    novo.foto = caminhoF;
                    novo.idUsuario = Convert.ToInt32(Session["idUsuario"]);
                    atual.Criar(novo);
                    return RedirectToAction("PerfilIni", "Usuarios");
                }

            }
        }
        [HttpPost]
        public ActionResult BuscarUsers(string buscando)
        {
            Usuarios user = new Usuarios();
            Bandas atuali = atual.PegaBanda(Session["idBanda"].ToString());
            Session["buscando"] = buscando;
            return View(atuali);
        }



        public ActionResult AdicionaIntegrante(int id)
        {
            atual.AdicionarIntegrante(id, Convert.ToInt32(Session["idBanda"]));
            return RedirectToAction("PerfilIni", "Usuarios");
        }

        public ActionResult removeUser(int idR)
        {
            atual.DeletarIntegrante(idR, Convert.ToInt32(Session["idBanda"]));
            return RedirectToAction("PerfilIni", "Usuarios");
        }

        public ActionResult Perfil(int id)
        {
            bool lider = false;
            string ids;
            ids = Convert.ToString(id);
            atual = atual.PegaBanda(ids);
            lider = atual.verificaUser(Convert.ToInt32(Session["idUsuario"]), id);
            if (lider == true)
            {
                Session["idBanda"] = id;
                Session["nomeBanda"] = atual.nome;
                return View("PerfilLiders", atual);
            }
            else
            {
                ViewBag.Seguindo = false;
                Session["idBanda"] = id;
                ViewBag.Seguindo = RedeMusica.Models.Usuarios.VerificaBandaSeguir(Convert.ToInt32(Session["idUsuario"]), Convert.ToInt32(Session["idBanda"]));
                return View(atual);
            }

        }

        public ActionResult unfollowBanda(int idBandaUnf)
        {
            Usuarios user = new Usuarios();
            user.UnfollowBanda(Convert.ToInt32(Session["idUsuario"]), idBandaUnf);
            return RedirectToAction("PerfilIni", "Usuarios");
        }

        public ActionResult followBanda(int idBandaf)
        {
            Usuarios user = new Usuarios();
            user.SeguirBanda(Convert.ToInt32(Session["idUsuario"]), idBandaf);
            return RedirectToAction("PerfilIni", "Usuarios");
        }
        public ActionResult BuscaUserBanda(string busca)
        {
            Bandas banda = new Bandas();
            Bandas atual = banda.PegaBanda(Session["idBanda"].ToString());
            Session["buscando"] = busca;
            return View(atual);
        }

        public ActionResult ConfigBanda()
        {
            if (Session["idUsuario"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            Bandas deAgora = atual.PegaBanda(Session["idBanda"].ToString());
            return View(deAgora);
        }

        public ActionResult DeleteBanda()
        {
            if (Session["idUsuario"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            atual.DeletarBanda(Convert.ToInt32(Session["idBanda"]));
  
            return RedirectToAction("PerfilIni", "Usuarios");
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult ConfigBanda(Bandas atual, HttpPostedFileBase fileImagem)
        {
            String caminhoF = null;
            Bandas qse = new Bandas();
            if (atual.nome == null || atual.cidadeNatal == null)
            {
                return View("ConfigBanda");
            }
            else
            {
                if (fileImagem != null && fileImagem.ContentLength > 0)
                {
                    string ext = Path.GetExtension(fileImagem.FileName);
                    if (!ext.Equals(".jpg", StringComparison.OrdinalIgnoreCase))
                    {
                        ViewBag.Imagem = "Somente imagens .jpg";
                        return View("ConfigBanda");
                    }
                    else
                    {
                        var fileName = Path.GetFileName(fileImagem.FileName);
                        string novas = fileName.Replace(" ", "");
                        var path = Path.Combine(Server.MapPath("~/ImagemBanda"), novas);
                        fileImagem.SaveAs(path);
                        caminhoF = "~/ImagemBanda/" + novas.ToString();
                        atual.foto = caminhoF;
                        qse.AtualizaFoto(atual);
                        qse.editar(atual);
                        return RedirectToAction("PerfilIni", "Usuarios");
                    }
                }

                else
                {
                    qse.editar(atual);
                    return RedirectToAction("PerfilIni", "Usuarios");
                }
            }

        }
    }
}

RedeMusica/Controllers/GaleriaController.cs
using System;
using ImageResizer;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RedeMusica.Models;
using System.IO;

namespace RedeMusica.Controllers
{
    public class GaleriaController : Controller
    {
        // GET: Galeria
        Galeria foto = new Galeria();
        public ActionResult AdicinarFoto()
        {
            if (Session["idUsuario"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        public ActionResult AdicinarFotoBanda()
        {
            return View();
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult AdicinarFotoBanda(Galeria novo, HttpPostedFileBase file)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            else
            {
                if (novo.descricao == null)
                    novo.descricao = "";
                if (file != null && file.ContentLength > 0)
                {

                    string ext = Path.GetExtension(file.FileName);
                    if (String.IsNullOrEmpty(ext) || !ext.Equals(".jpg", StringComparison.OrdinalIgnoreCase) || file == null)
                    {
                        ViewBag.ImagemF = "Somente imagens .jpg";
                        return View("AdicinarFotoBanda");
                    }
                    var fileName = Path.GetFileName(file.FileName);
                    string nova = fileName.Replace(" ", "");
                    var path = Path.Combine(Server.MapPath("~/ImagemGaleria"), nova);
                    file.SaveAs(path);
                    String caminho = "~/ImagemGaleria/" + nova.ToString();
                    novo.arquivoFoto = caminho;
                    novo.usuarioId = Convert.ToString(Session["idBanda"]);
                    var thumbnail = new ImageJob(file, "~/Thumbnails/<guid>", new Instructions("mode=max;format=jpg;width=300;height=300;"));
                    thumbnail.CreateParentDirectory = true;
                    thumbnail.AddFileExtension = true;
                    thumbnail.Build();
                    fileName = Path.GetFileName(thumbnail.FinalPath);
                    novo.thumbnail = Url.Content("~/Thumbnails/" + fileName);
                    foto.AdicionarFotoBanda(novo);
                }
                else
                {
                    ViewBag.ImagemF = "Somente imagens .jpg";
                    return View("AdicinarFotoBanda");
                }
                int numero = Convert.ToInt32(Session["idBanda"]);
                return RedirectToAction("Perfil", "Bandas", new { id = numero });
            }
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult AdicinarFoto(Galeria novo, HttpPostedFileBase file)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            else
            {
                if (novo.descricao == null)
                    novo.descricao = "Sem legenda";
                if (file != null && file.ContentLength > 0)
                {

                    string ext = Path.GetExtension(file.FileName);
                    if (String.IsNullOrEmpty(ext) || !ext.Equals(".jpg", StringComparison.OrdinalIgnoreCase) || file== null)
                    {
                        ViewBag.ImagemF = "Somente imagens .jpg";
                        return View("AdicinarFoto");
                    }
                    var fileName = Path.GetFileName(file.FileName);
                    string nova = fileName.Replace(" ", "");
                    var path = Path.Combine(Server.MapPath("~/ImagemGaleria"), nova);
                    file.SaveAs(path);
                    String caminho = "~/ImagemGaleria/" + nova.ToString();
                    novo.arquivoFoto = caminho;
                    novo.usuarioId = Convert.ToString(Session["idUsuario"]) ;
                    var thumbnail = new ImageJob(file, "~/Thumbnails/<guid>", new Instructions("mode=max;format=jpg;width=300;height=300;"));
                    thumbnail.CreateParentDirectory = true;
                    thumbnail.AddFileExtension = true;
                    thumbnail.Build();
                    fileName = Path.GetFileName(thumbnail.FinalPath);
                    novo.thumbnail = Url.Content("~/Thumbnails/" + fileName);
                    foto.Adicionar(novo);
                }
                else
                {
                    ViewBag.ImagemF = "Somente imagens .jpg";
                    return View("AdicinarFoto");
                }
                return RedirectToAction("PerfilIni", "Usuarios");
            }

        }
        public ActionResult DeleteFoto()
        {
            if (Session["idUsuario"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            List<RedeMusica.Models.Galeria> listaFotos = new List<RedeMusica.Models.Galeria>();
            listaFotos = foto.getUserFotos(Convert.ToInt32(Session["idUsuario"]));
            return View(listaFotos);

        }
        public ActionResult DeleteFotoBanda()
        {
            if (Session["idUsuario"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            List<RedeMusica.Models.Galeria> listaFotos = new List<RedeMusica.Models.Galeria>();
            listaFotos = foto.getBandaFotos(Convert.ToInt32(Session["idBanda"]));
            return View(listaFotos);

        }
        public ActionResult DeleteFotosB(int id)
        {
            foto.Delete(id);
            return RedirectToAction("DeleteFotoBanda");
        }


        public ActionResult DeleteFotos(int id)
        {
            foto.Delete(id);
            return RedirectToAction("DeleteFoto");
        }


    }
}

RedeMusica/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using RedeMusica.Models;
using System.Web.Mvc;

namespace RedeMusica.Controllers
{
    public class PostsController : Controller
    {

        Posts atual = new Posts();
        // GET: Posts
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CriarPost()
        {
            if (Session["idUsuario"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        public ActionResult CriarPostBanda()
        {
            if (Session["idUsuario"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult CriarPostBanda(Posts novo)
        {
            if (!ModelState.IsValid)
            {
                return View("CriarPostBanda");
            }
            novo.usuarioId = Convert.ToInt64(Session["idBanda"]);
            atual.CriarNovoBanda(novo);
            return RedirectToAction("Perfil", "Bandas", new { id = novo.usuarioId });
        }

       [AcceptVerbs(HttpVerbs.Post)]
         public ActionResult CriarPost(Posts novo)
        {
            if (!ModelState.IsValid)
            {
                return View("CriarPost");
            }
            novo.usuarioId = Convert.ToInt64(Session["idUsuario"]);
            atual.CriarNovo(novo);
            return RedirectToAction("PerfilIni","Usuarios");    
        }

        public ActionResult ListaPropriosPosts()
        {
            List<Posts> Lista = new List<Posts>();
           Lista= atual.getPosts(Convert.ToInt32(Session["idUsuario"]));
            return View(Lista);

        }
        
        public ActionResult Delete(int idPosts)
        {
            atual.Delete(idPosts);
            return RedirectToAction("PerfilIni", "Usuarios");
        }
    }
}

RedeMusica/Views/Bandas/BuscaUserBanda.cshtml
@model RedeMusica.Models.Bandas
@{
    ViewBag.Title = "BuscandoUsers";
    string foto = Model.foto;
}

<h2>Perfil Banda</h2>
<div class="col col-sm-3">
    <div class="row">
        <div>
            <div id="sidebar">
                <ul class="nav nav-stacked">
                    <li><h3 class="highlight">@Html.DisplayFor(atual => Model.nome) </h3></li>
                    <li><img src=@Url.Content(foto) style="width:128px;height:128px" /> </li>
                    <li>@Html.DisplayFor(atual => Model.cidadeNatal)</li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="col col-sm-9">
    <div class="container">
        <div id="content">
            <ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
                <li class="active"><a href="#red" data-toggle="tab">Usuários</a></li>
            </ul>
            <div id="my-tab-content" class="tab-content">
                <div class="tab-pane active" id="red">
                    <h1>Musicas</h1>
                    <br />
                    @{
                        RedeMusica.Models.Usuarios user = new RedeMusica.Models.Usuarios();
                        List<RedeMusica.Models.Usuarios> listaM = new List<RedeMusica.Models.Usuarios>();
                        listaM = RedeMusica.Models.Usuarios.BuscaUser(Session["buscando"].ToString());
                    }

                    <p>
                        @Html.ActionLink("Create New", "MusicaUsuario", "Musicas")
                    </p>
                    <table style="table-layout: fixed; width: 400px">


                        @foreach (var item in listaM)
                        {
                            string fotoM = item.imageMusica.ToString();
                            string musica = item.arquivoMusica.ToString();



                            <tr>
                                <th rowspan="4"> <img src=@Url.Content(fotoM) style="width:128px;height:128px" /> </th>
                                <th colspan="2">@Html.DisplayFor(modelItem => item.nome)</th>
                            </tr>
                            <tr>
                                <td colspan="2">@Html.DisplayFor(modelItem => item.usuarioNome)</td>
                            </tr>
                            <tr>
                                <td colspan="2">
                                    <audio controls id="audioplayer">
                                        <source src=@Url.Content(musica) type="audio/mp3" />
                                        sem audio
                                    </audio>
                                </td>
                            </tr>
                            <tr>
                                <td>Ouvida @Html.DisplayFor(modelItem => item.nOuvida)</td>
                                <td>@Html.DisplayFor(modelItem => item.dataPost)</td>
                            </tr>

                        }

                    </table>
                </div>

RedeMusica/Views/Bandas/BuscarUsers.cshtml
@model RedeMusica.Models.Bandas
@{
    ViewBag.Title = "busca";
    string foto = Model.foto;
}

<br />
<br />
<div class="container">
    <div class="row">
        <div class="col col-sm-3">
            <div>
                <div id="sidebar">
                    <ul class="nav nav-stacked">
                        <li><h3 class="highlight">@Html.DisplayFor(atual => Model.nome)  </h3></li>
                        <li><img src=@Url.Content(foto) style="width:200px;height:200px" /> </li>
                        <li>@Html.DisplayFor(atual => Model.cidadeNatal)</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col col-sm-7">
            <div id="content">
                <ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
                    <li class="active"><a href="#orange" data-toggle="tab">Usuários</a></li>
                    
                </ul>
                <div id="my-tab-content" class="tab-content">

                    <div class="tab-pane active" id="orange">

                        @{
                            RedeMusica.Models.Bandas banda = new RedeMusica.Models.Bandas();
                            List<RedeMusica.Models.Usuarios> listaUsers = new List<RedeMusica.Models.Usuarios>();
                            listaUsers = banda.buscaUser(Convert.ToInt32(Session["idBanda"]),Session["buscando"].ToString(),Convert.ToInt32(Session["idUsuario"]));
                        }

                        @foreach (var item in listaUsers)
                        {
                            string fotoPosts = item.fotoPerfil.ToString();
                            string nome = item.nome;
                            <br />
                            <div class="media">
                                <a class="media-left pull-left" href="#">
                                    <img src=@Url.Content(fotoPosts) style="width:128px;height:128px">
                                </a>
                                <div class="media-body">
                                    <h4 class="media-heading">@Html.ActionLink(nome, "Perfil", "Usuarios", new { id = item.id }, null)</h4>
                                     @Html.ActionLink("Adicionar a Banda","AdicionaIntegrante", new{id=item.id})
                                </div>
                            </div>
                        }


                    </div>
                    
                    
                    
                </div>
            </div>
        </div>
    </div>
</div>

RedeMusica/Views/Bandas/ConfigBanda.cshtml
@model RedeMusica.Models.Bandas

@{
    ViewBag.Title = "Config";
}

<h2>Config Bandas</h2>
<br />
<p>@Html.ActionLink("Deletar Banda", "DeleteBanda", "Bandas")</p>
<br />
@using (Html.BeginForm("ConfigBanda", "Bandas", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cidadeNatal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cidadeNatal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cidadeNatal, "", new { @class = "text-danger" })
            </div>
        </div>

       
        <div style="margin-left:2%">
            Imagem: <input type="file" name="fileImagem" />
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Editar" class="btn btn-default" />
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
@if (ViewBag.Imagem != null)
{
    <script type="text/javascript">



        alert('@ViewBag.Imagem');



    </script>
}

RedeMusica/Views/Bandas/PerfilLiders.cshtml
@model RedeMusica.Models.Bandas
@{
    ViewBag.Title = "PerfiLiders";
    string foto = Model.foto;
}
<h2>Administrador da banda</h2>
<br />
<br />
<div class="container">
    <div class="row">
        <div class="col col-sm-3">
            <div>
                <div id="sidebar">
                    <ul class="nav nav-stacked">
                        <li><h3 class="highlight">@Html.DisplayFor(atual => Model.nome) </h3></li>
                        <li><img src=@Url.Content(foto) style="width:200px;height:200px" /> </li>
                        <li>@Html.DisplayFor(atual => Model.cidadeNatal)</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col col-sm-7">
            <div id="content">
                <ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
                    <li class="active"><a href="#red" data-toggle="tab">Músicas</a></li>
                    <li><a href="#green" data-toggle="tab">Galeria</a></li>
                    <li><a href="#gray" data-toggle="tab">Postagens</a></li>
                    <li><a href="#RadioLadio" data-toggle="tab">Integrantes</a></li>
                </ul>
                <div id="my-tab-content" class="tab-content">

                    <div class="tab-pane active" id="red">
                        <br />
                        <p>@Html.ActionLink("Adicionar nova música", "MusicaBanda", "Musicas")</p>

                        <br />
                        @{
                            RedeMusica.Models.Musicas Musica = new RedeMusica.Models.Musicas();
                            List<RedeMusica.Models.Musicas> listaM = new List<RedeMusica.Models.Musicas>();
                            listaM = Musica.PropriasBanda(Convert.ToInt32(Session["idBanda"]));
                        }

                        <table style="table-layout: fixed; width: 400px">


                            @foreach (var item in listaM)
                            {
                                string fotoM = item.imageMusica.ToString();
                                string musica = item.arquivoMusica.ToString();
                                string data = item.dataPost.ToShortDateString();
                                string nome = item.usuarioNome;

                                <tr>
                                    <th rowspan="4"> <img src=@Url.Content(fotoM) style="width:128px;height:128px" /> </th>
                                    <th colspan="2">@Html.DisplayFor(modelItem => item.nome) @Html.ActionLink("Deletar", "DeleteMusica", "Musicas", new { idM = item.id }, null)</th>

                                </tr>
                                <tr>
                                    <td colspan="2">@Html.DisplayFor(modelItem => item.usuarioNome)</td>
                                </tr>
                                <tr>
                                    <td colspan="2">
                                        <audio controls id="audioplayer">
                                            <source src=@Url.Content(musica) type="audio/mp3" />
                                            sem audio
                                        </audio>
                                    </td>
                                </tr>
                                <tr>
                                    <td> @Html.DisplayFor(modelItem => item.estiloNome)</td>
                                    <td>@data</td>
                                </tr>
                                <tr>
                                    <td><br /></td>
                                </tr>

                            }
                        </table>
                    </div>

              
                    <div class="tab-pane" id="green">
                        <br />
                        @Html.ActionLink("Deletar", "DeleteFotoBanda", "Galeria")
                        <p>@Html.ActionLink("Adicionar nova Foto", "AdicinarFotoBanda", "Galeria")</p>
                        <br />
                        <div class="clearfix">
                            <ul class="grid list-unstyled">

                                @{
                                    RedeMusica.Models.Galeria fotoUser = new RedeMusica.Models.Galeria();
                                    List<RedeMusica.Models.Galeria> listaFoto = new List<RedeMusica.Models.Galeria>();
                                    listaFoto = fotoUser.getBandaFotos(Convert.ToInt32(Session["idBanda"]));
                                }
                                @foreach (var item in listaFoto)
                                {
                                    string fotoG = item.arquivoFoto.ToString();
                                    string thumb = item.thumbnail.ToString();

                                    <li class="col-sm-3">
                                        <a href=@Url.Content(fotoG) data-caption="@item.descricao">
                                            <img style="width: 100%" src=@Url.Content(thumb)>
                                        </a>
                                    </li>
                                }
                            </ul>
                        </div>
                    </div>


                    <div class="tab-pane" id="gray">
                        <br />
                        <p>@Html.ActionLink("Adicionar novo post", "CriarPostBanda", "Posts")</p>
                        @{
                            RedeMusica.Models.Posts postsBanda = new RedeMusica.Models.Posts();
                            List<RedeMusica.Models.Posts> listaPostsProprios = new List<RedeMusica.Models.Posts>();
                            listaPostsProprios = postsBanda.getPostsBanda(Convert.ToInt32(Session["idBanda"]));
                        }


                        @foreach (var item in listaPostsProprios)
                        {
                            string fotoPosts = item.imagem.ToString();
                            string nome = item.nome;
                            <br />
                            <div class="media">
                                <a class="media-left pull-left" href="#">
                                    <img src=@Url.Content(fotoPosts) style="width:128px;height:128px">
                                </a>
                                <div class="media-body">
                                    <h4 class="media-heading">@Html.DisplayFor(modelItem => item.nome)</h4>
                                    @item.texto @Html.ActionLink("Deletar", "Delete", "Posts", new { idPosts = item.idPost }, null)
                                </div>
                            </div>
                        }


                    </div>

                    <div class="tab-pane" id="RadioLadio">
                        @Html.ActionLink("Editar Banda", "ConfigBanda")
                        <br />
                        @using (Html.BeginForm("BuscarUsers", "Bandas", FormMethod.Post))
                        {
                            <div>
                                <input type="text" class="form-control" placeholder="Busque usuários para sua banda" style="width:700px" name="buscando" id="buscando">
                            </div>
                        }
                        
                        
                         @{
                            RedeMusica.Models.Bandas integrantes = new RedeMusica.Models.Bandas();
                            List<RedeMusica.Models.Usuarios> listasIntegrantes = new List<RedeMusica.Models.Usuarios>();
                            listasIntegrantes = integrantes.getIntegrantesLider(Convert.ToInt32(Session["idBanda"]),Convert.ToInt32(Session["idUsuario"]));
                        }

                        @foreach (var item in listasIntegrantes)
                        {
                            string fotoPosts = item.fotoPerfil.ToString();
                            string nome = item.nome;
                            <br />
                            <div class="media">
                                <a class="media-left pull-left" href="#">
                                    <img src=@Url.Content(fotoPosts) style="width:128px;height:128px">
                                </a>
                                <div class="media-body">
                                    <h4 class="media-heading">@Html.ActionLink(nome, "Perfil", "Usuarios", new { id = item.id }, null)</h4>
                                    @Html.ActionLink("Remover usuario","removeUser", new{idR=item.id})
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>